import { execFile } from "child_process";
import { promisify } from "util";
import type { SoftBanHit } from "./verify/write-policy.ts";

const execFileAsync = promisify(execFile);

export interface PrBodyInput {
  issueNumber: number;
  issueTitle: string;
  bugSummary: string;
  rootCause: string;
  fixSummary: string;
  filesChanged: string[];
  testFilesAdded: string[];
  ciStatus: "passed" | "failed" | "skipped";
  fixAttempts: number;
  softBanTouched: SoftBanHit[];
  handoffMarkdown: string;
}

const FOOTER = "🤖 generated by rolenext-bug-resolver";

const SOFT_BAN_CATEGORY_LABELS: Record<string, string> = {
  specs: "**spec changes** — review whether the spec needed updating, or the code should match the spec",
  build: "**build config** — verify CI implications",
  compose: "**docker-compose** — verify dev/CI implications",
  deps: "**dependency manifest** — verify the dependency change is intentional",
  other: "**watched path**",
};

/** Build the PR body markdown from structured task outputs. */
export function buildPrBody(input: PrBodyInput): string {
  const lines: string[] = [];

  lines.push(`## Bug`);
  lines.push("");
  lines.push(input.bugSummary.trim() || `Bug reported in issue #${input.issueNumber}.`);
  lines.push("");
  lines.push(`Closes #${input.issueNumber}`);
  lines.push("");

  if (input.softBanTouched.length > 0) {
    lines.push(`## ⚠️ Soft-ban paths touched`);
    lines.push("");
    lines.push("This fix touched paths the bot is normally cautious about. Extra scrutiny recommended:");
    lines.push("");
    for (const hit of input.softBanTouched) {
      const cat = SOFT_BAN_CATEGORY_LABELS[hit.category] ?? `**${hit.category}**`;
      lines.push(`- \`${hit.path}\` — ${cat}`);
    }
    lines.push("");
  }

  lines.push(`## Root cause`);
  lines.push("");
  lines.push(input.rootCause.trim() || "_See handoff._");
  lines.push("");

  lines.push(`## Fix`);
  lines.push("");
  lines.push(input.fixSummary.trim() || "_See diff._");
  lines.push("");

  lines.push(`## Verification`);
  lines.push("");
  const ciCheck = input.ciStatus === "passed" ? "x" : " ";
  const testCheck = input.testFilesAdded.length > 0 ? "x" : " ";
  lines.push(`- [${ciCheck}] \`make ci\` ${input.ciStatus}`);
  lines.push(
    `- [${testCheck}] regression test added (${input.testFilesAdded.length} file${input.testFilesAdded.length === 1 ? "" : "s"})`,
  );
  if (input.fixAttempts > 1) {
    lines.push(`- bot used ${input.fixAttempts} fix attempts (retried after CI failure)`);
  }
  lines.push("");

  if (input.filesChanged.length > 0) {
    lines.push(`## Files changed`);
    lines.push("");
    for (const f of input.filesChanged) lines.push(`- \`${f}\``);
    lines.push("");
  }

  if (input.testFilesAdded.length > 0) {
    lines.push(`## Tests added / modified`);
    lines.push("");
    for (const f of input.testFilesAdded) lines.push(`- \`${f}\``);
    lines.push("");
  }

  lines.push(`<details><summary>handoff.md (full triage + fix log)</summary>`);
  lines.push("");
  lines.push(input.handoffMarkdown.trim());
  lines.push("");
  lines.push(`</details>`);
  lines.push("");
  lines.push(`---`);
  lines.push(FOOTER);

  return lines.join("\n");
}

/** Push the worktree's branch to origin. */
export async function pushBranch(worktreePath: string, branch: string): Promise<void> {
  await execFileAsync("git", ["push", "-u", "origin", branch], {
    cwd: worktreePath,
    encoding: "utf-8",
    maxBuffer: 10 * 1024 * 1024,
    timeout: 120_000,
  });
}

/** Derive a short "area" string from the touched files for the PR title. */
export function deriveArea(filesChanged: string[]): string {
  // Most-impacted top-level directory (e.g. "backend/handler.go" → "backend").
  // For nested directories, prefer the second segment if more specific (e.g. "frontend/src/pages/X.tsx" → "frontend").
  const segCounts = new Map<string, number>();
  for (const f of filesChanged) {
    const top = f.split("/")[0];
    if (!top) continue;
    segCounts.set(top, (segCounts.get(top) ?? 0) + 1);
  }
  if (segCounts.size === 0) return "fix";
  return [...segCounts.entries()].sort((a, b) => b[1] - a[1])[0][0];
}

/** Build a PR title in the canonical shape. */
export function buildPrTitle(area: string, summary: string, issueNumber: number): string {
  // Trim summary to ~60 chars and strip newlines.
  const clean = summary
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 60);
  return `fix(${area}): ${clean} [#${issueNumber}]`;
}
